[package]
name = "basic"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
#pub = "0.3.4"
serde = { version = "1.0.219", features = ["derive"] }
time = { version = "0.3.41", features = ["serde", "macros","parsing","formatting"] }
tokio = {version = "1.45.1", features = ["full"]}
